sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ivorobioff/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ivorobioff/docker-react

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-337737044543
  bucket_path: docker-react
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
