sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t ivorobioff/docker-react -f Dockerfile.env .

script:
  - docker run -e CI=true ivorobioff/docker-react npm run test